import { isDemoMode } from "../config";
import { db } from "../db/client";
import { posts } from "../demo-data";
import type { Post,WorkflowRunResult } from "../types";
import { mapPost } from "./workspace-snapshot";

export async function recordAgentRun(i:{workspaceId:string;actorId:string;objective:string;output:unknown;trace:unknown}){if(isDemoMode()||i.workspaceId==="demo-workspace")return;const sql=db();await sql`insert into agent_runs(workspace_id,actor_id,objective,tool_trace,output) values(${i.workspaceId}::uuid,${i.actorId},${i.objective},${sql.json(i.trace as any)},${sql.json(i.output as any)})`}
export async function getPost(workspaceId:string,postId:string):Promise<Post|null>{if(isDemoMode()||workspaceId==="demo-workspace")return posts.find(p=>p.id===postId)??null;const sql=db();const rows=await sql<Array<Record<string,unknown>>>`select p.*,coalesce(ca.kind,'text') as asset_type from posts p left join content_assets ca on ca.id=p.asset_id where p.workspace_id=${workspaceId}::uuid and p.id=${postId}::uuid limit 1`;return rows[0]?mapPost(rows[0]):null}
export async function hasEntityApproval(workspaceId:string,entityType:string,entityId:string){if(isDemoMode()||workspaceId==="demo-workspace")return false;const sql=db();const rows=await sql<Array<{approved:boolean}>>`select exists(select 1 from approvals where workspace_id=${workspaceId}::uuid and entity_type=${entityType} and entity_id=${entityId}::uuid and status='approved') as approved`;return Boolean(rows[0]?.approved)}
export async function decideApproval(i:{workspaceId:string;entityType:string;entityId:string;userId:string;decision:"approved"|"rejected";comment?:string}){if(isDemoMode()||i.workspaceId==="demo-workspace")return{id:`demo-approval-${i.entityId}`,status:i.decision};const sql=db();const rows=await sql<Array<{id:string;status:string}>>`insert into approvals(workspace_id,entity_type,entity_id,status,requested_by,decided_by,decided_at,comment) values(${i.workspaceId}::uuid,${i.entityType},${i.entityId}::uuid,${i.decision},${i.userId},${i.userId},now(),${i.comment??null}) on conflict(workspace_id,entity_type,entity_id) do update set status=excluded.status,decided_by=excluded.decided_by,decided_at=now(),comment=excluded.comment returning id::text as id,status`;if(i.entityType==="post")await sql`update posts set approved_by=${i.decision==="approved"?i.userId:null},approved_at=${i.decision==="approved"?new Date().toISOString():null},status=case when ${i.decision}='approved' and scheduled_at is not null then 'scheduled'::post_status else 'draft'::post_status end,updated_at=now() where workspace_id=${i.workspaceId}::uuid and id=${i.entityId}::uuid`;await sql`insert into audit_log(workspace_id,actor_id,action,entity_type,entity_id,detail) values(${i.workspaceId}::uuid,${i.userId},${`approval.${i.decision}`},${i.entityType},${i.entityId},${sql.json({comment:i.comment??null})})`;return rows[0]}
export async function recordWorkflowRun(workspaceId:string,workflowId:string,result:WorkflowRunResult,triggerPayload:Record<string,unknown>){if(isDemoMode()||workspaceId==="demo-workspace")return;const sql=db();await sql`insert into workflow_runs(id,workflow_id,workspace_id,status,trigger_payload,step_results,started_at,finished_at) values(${result.runId.replace(/^run_/,"")}::uuid,${workflowId}::uuid,${workspaceId}::uuid,${result.status},${sql.json(triggerPayload)},${sql.json(result.stepResults as any)},${result.startedAt},${result.finishedAt??null})`}
