import { analyticsSnapshot,campaigns,dashboardMetrics,posts,products,workflows } from "../demo-data";
import { isDemoMode } from "../config";
import { db } from "../db/client";
import type { AnalyticsSnapshot,Campaign,DashboardMetric,Post,Product,SocialChannel,WorkflowDefinition } from "../types";

export interface WorkspaceSnapshot{dashboardMetrics:DashboardMetric[];campaigns:Campaign[];posts:Post[];workflows:WorkflowDefinition[];analytics:AnalyticsSnapshot;products:Product[]}
const iso=(value:unknown)=>value?new Date(String(value)).toISOString():new Date().toISOString();
const mapCampaign=(r:Record<string,unknown>):Campaign=>({id:String(r.id),name:String(r.name??"Untitled campaign"),objective:String(r.objective??""),status:(r.status??"planning") as Campaign["status"],channels:(r.channels??[]) as SocialChannel[],startAt:iso(r.starts_at),endAt:iso(r.ends_at),posts:Number(r.post_count??0),spend:r.spend==null?undefined:Number(r.spend),revenue:r.revenue==null?undefined:Number(r.revenue)});
export const mapPost=(r:Record<string,unknown>):Post=>({id:String(r.id),channel:r.channel as SocialChannel,title:String(r.title??""),copy:String(r.copy??""),status:(r.status??"draft") as Post["status"],scheduledAt:iso(r.scheduled_at),campaignId:String(r.campaign_id??""),assetType:(r.asset_type??"text") as Post["assetType"],impressions:r.impressions==null?undefined:Number(r.impressions),clicks:r.clicks==null?undefined:Number(r.clicks),conversions:r.conversions==null?undefined:Number(r.conversions)});
const mapWorkflow=(r:Record<string,unknown>):WorkflowDefinition=>{const d=(r.definition??{}) as Partial<WorkflowDefinition>;return{id:String(r.id),name:String(r.name??"Untitled workflow"),description:String(r.description??""),trigger:String(r.trigger_type??"manual") as WorkflowDefinition["trigger"],enabled:Boolean(r.enabled),steps:Array.isArray(d.steps)?d.steps:[],lastRunAt:r.last_run_at?iso(r.last_run_at):undefined,runCount:Number(r.run_count??0)}};

export async function getWorkspaceSnapshot(workspaceId:string):Promise<WorkspaceSnapshot>{
 if(isDemoMode()||workspaceId==="demo-workspace")return{dashboardMetrics,campaigns,posts,workflows,analytics:analyticsSnapshot,products};
 const sql=db();
 const [cr,pr,wr,xr,er]=await Promise.all([
  sql<Array<Record<string,unknown>>>`select c.*,count(distinct p.id)::int as post_count,coalesce(sum(case when ae.event_type='revenue' then ae.value else 0 end),0) as revenue,coalesce(sum(case when ae.event_type='spend' then ae.value else 0 end),0) as spend from campaigns c left join posts p on p.campaign_id=c.id left join analytics_events ae on ae.post_id=p.id where c.workspace_id=${workspaceId}::uuid group by c.id order by c.created_at desc`,
  sql<Array<Record<string,unknown>>>`select p.*,coalesce(ca.kind,'text') as asset_type,coalesce(sum(case when ae.event_type='impression' then ae.value else 0 end),0) as impressions,coalesce(sum(case when ae.event_type='click' then ae.value else 0 end),0) as clicks,coalesce(sum(case when ae.event_type='conversion' then ae.value else 0 end),0) as conversions from posts p left join analytics_events ae on ae.post_id=p.id left join content_assets ca on ca.id=p.asset_id where p.workspace_id=${workspaceId}::uuid group by p.id,ca.kind order by p.scheduled_at nulls last,p.created_at desc`,
  sql<Array<Record<string,unknown>>>`select w.*,count(r.id)::int as run_count,max(r.started_at) as last_run_at from workflows w left join workflow_runs r on r.workflow_id=w.id where w.workspace_id=${workspaceId}::uuid group by w.id order by w.created_at desc`,
  sql<Array<Record<string,unknown>>>`select id::text,external_id,source,title,description,price,currency,inventory,image_url,tags,updated_at from products where workspace_id=${workspaceId}::uuid order by updated_at desc`,
  sql<Array<{event_type:string;total:string}>>`select event_type,coalesce(sum(value),0)::text as total from analytics_events where workspace_id=${workspaceId}::uuid group by event_type`
 ]);
 const totals=new Map(er.map(r=>[r.event_type,Number(r.total)]));
 const analytics:AnalyticsSnapshot={impressions:totals.get("impression")??0,engagements:totals.get("engagement")??0,clicks:totals.get("click")??0,conversions:totals.get("conversion")??0,revenue:totals.get("revenue")??0,spend:totals.get("spend")??0,followersGained:totals.get("follower")??0};
 const metrics:DashboardMetric[]=[{label:"Revenue influenced",value:`$${analytics.revenue.toLocaleString()}`,change:"live",direction:"flat",helper:"from persisted attribution events"},{label:"Social conversions",value:analytics.conversions.toLocaleString(),change:"live",direction:"flat",helper:"persisted conversions"},{label:"Qualified clicks",value:analytics.clicks.toLocaleString(),change:"live",direction:"flat",helper:"to owned properties"},{label:"Content velocity",value:String(pr.filter(r=>r.status==="published").length),change:"live",direction:"flat",helper:"published posts in workspace"}];
 return{dashboardMetrics:metrics,campaigns:cr.map(mapCampaign),posts:pr.map(mapPost),workflows:wr.map(mapWorkflow),analytics,products:xr.map(r=>({id:String(r.id),externalId:r.external_id?String(r.external_id):undefined,source:r.source as Product["source"],title:String(r.title??""),description:String(r.description??""),price:Number(r.price??0),currency:String(r.currency??"USD"),imageUrl:r.image_url?String(r.image_url):undefined,inventory:r.inventory==null?undefined:Number(r.inventory),tags:(r.tags??[]) as string[],updatedAt:iso(r.updated_at)}))};
}

export async function findProducts(workspaceId:string,query:string):Promise<Product[]>{const snapshot=await getWorkspaceSnapshot(workspaceId);const q=query.toLowerCase();const matches=snapshot.products.filter(p=>[p.title,p.description,...p.tags].join(" ").toLowerCase().includes(q));return matches.length?matches:snapshot.products.slice(0,2)}
export async function getBrandContext(workspaceId:string){if(isDemoMode()||workspaceId==="demo-workspace")return{voice:"confident, useful, modern, never overhyped",audience:"design-conscious shoppers ages 25-44",prohibitedClaims:["unverified sustainability claims","guaranteed outcomes"],winningThemes:["versatility","quality materials","practical design"]};const sql=db();const rows=await sql<Array<{voice:Record<string,unknown>;guardrails:Record<string,unknown>;strategy_memory:Record<string,unknown>}>>`select voice,guardrails,strategy_memory from brands where workspace_id=${workspaceId}::uuid order by created_at asc limit 1`;return rows[0]??{voice:{},guardrails:{},strategy_memory:{}}}
